<?php

use Illuminate\Database\Seeder;

class LanguagesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::select("INSERT INTO `languages` (`code`, `name`, `native`, `rtl`) VALUES
  ('sa', 'Arabic', 'العربية', '1'),
  ('et', 'Amharic', 'አማርኛ', '0'),
  ('pe', 'Aymara', 'Aymar', '0'),
  ('az', 'Azerbaijani', 'Azərbaycanca / آذربايجان', '0'),
  ('by', 'Belarusian', 'Беларуская', '0'),
  ('bg', 'Bulgarian', 'Български', '0'),
  ('vu', 'Bislama', 'Bislama', '0'),
  ('bd', 'Bengali', 'বাংলা', '0'),
  ('ba', 'Bosnian', 'Bosanski', '0'),
  ('ad', 'Catalan', 'Català', '0'),
  ('mp', 'Chamorro', 'Chamoru', '0'),
  ('cz', 'Czech', 'Česky', '0'),
  ('dk', 'Danish', 'Dansk', '0'),
  ('de', 'German', 'Deutsch', '0'),
  ('mv', 'Divehi', 'ދިވެހިބަސް', '1'),
  ('bt', 'Dzongkha', 'ཇོང་ཁ', '0'),
  ('gr', 'Greek', 'Ελληνικά', '0'),
  ('us', 'English USA', 'English', '0'),
  ('gb', 'English UK', 'English', '0'),
  ('es', 'Spanish', 'Español', '0'),
  ('ee', 'Estonian', 'Eesti', '0'),
  ('ir', 'Persian', 'فارسی', '1'),
  ('sn', 'Peul', 'Fulfulde', '0'),
  ('fi', 'Finnish', 'Suomi', '0'),
  ('fj', 'Fijian', 'Na Vosa Vakaviti', '0'),
  ('fo', 'Faroese', 'Føroyskt', '0'),
  ('fr', 'French', 'Français', '0'),
  ('ie', 'Irish', 'Gaeilge', '0'),
  ('py', 'Guarani', 'Avañe''ẽ', '0'),
  ('im', 'Manx', 'Gaelg', '0'),
  ('il', 'Hebrew', 'עברית', '1'),
  ('in', 'Hindi', 'हिन्दी', '0'),
  ('hr', 'Croatian', 'Hrvatski', '0'),
  ('ht', 'Haitian', 'Krèyol ayisyen', '0'),
  ('hu', 'Hungarian', 'Magyar', '0'),
  ('am', 'Armenian', 'Հայերեն', '0'),
  ('id', 'Indonesian', 'Bahasa Indonesia', '0'),
  ('is', 'Icelandic', 'Íslenska', '0'),
  ('it', 'Italian', 'Italiano', '0'),
  ('jp', 'Japanese', '日本語', '0'),
  ('ge', 'Georgian', 'ქართული', '0'),
  ('ao', 'Kongo', 'KiKongo', '0'),
  ('kz', 'Kazakh', 'Қазақша', '0'),
  ('gl', 'Greenlandic', 'Kalaallisut', '0'),
  ('kh', 'Cambodian', 'ភាសាខ្មែរ', '0'),
  ('kp', 'North Korea', '한국어', '0'),
  ('kr', 'South Korea', '한국어', '0'),
  ('kg', 'Kirghiz', 'Kırgızca / Кыргызча', '0'),
  ('lu', 'Luxembourgish', 'Lëtzebuergesch', '0'),
  ('cd', 'Lingala', 'Lingála', '0'),
  ('la', 'Laotian', 'ລາວ / Pha xa lao', '0'),
  ('lt', 'Lithuanian', 'Lietuvių', '0'),
  ('lv', 'Latvian', 'Latviešu', '0'),
  ('mg', 'Malagasy', 'Malagasy', '0'),
  ('mh', 'Marshallese', 'Kajin Majel / Ebon', '0'),
  ('nz', 'Maori', 'Māori', '0'),
  ('mk', 'Macedonian', 'Македонски', '0'),
  ('mn', 'Mongolian', 'Монгол', '0'),
  ('my', 'Malay', 'Bahasa Melayu', '0'),
  ('mt', 'Maltese', 'bil-Malti', '0'),
  ('mm', 'Burmese', 'Myanmasa', '0'),
  ('nr', 'Nauruan', 'Dorerin Naoero', '0'),
  ('np', 'Nepali', 'नेपाली', '0'),
  ('nl', 'Dutch', 'Nederlands', '0'),
  ('no', 'Norwegian', 'Norsk (bokmål / riksmål)', '0'),
  ('za', 'South Ndebele', 'isiNdebele', '0'),
  ('zm', 'Chichewa', 'Chi-Chewa', '0'),
  ('pl', 'Polish', 'Polski', '0'),
  ('af', 'Pashto', 'پښتو', '1'),
  ('pt', 'Portuguese', 'Português', '0'),
  ('bi', 'Kirundi', 'Kirundi', '0'),
  ('ro', 'Romanian', 'Română', '0'),
  ('ru', 'Russian', 'Русский', '0'),
  ('rw', 'Rwandi', 'Kinyarwandi', '0'),
  ('cf', 'Sango', 'Sängö', '0'),
  ('lk', 'Sinhalese', 'සිංහල', '0'),
  ('sk', 'Slovak', 'Slovenčina', '0'),
  ('sl', 'Slovenian', 'Slovenščina', '0'),
  ('ws', 'Samoan', 'Gagana Samoa', '0'),
  ('zw', 'Shona', 'chiShona', '0'),
  ('so', 'Somalia', 'Soomaaliga', '0'),
  ('al', 'Albanian', 'Shqip', '0'),
  ('rs', 'Serbian', 'Српски', '0'),
  ('sz', 'Swati', 'SiSwati', '0'),
  ('ls', 'Southern Sotho', 'Sesotho', '0'),
  ('se', 'Swedish', 'Svenska', '0'),
  ('tj', 'Tajik', 'Тоҷикӣ', '0'),
  ('th', 'Thai', 'ไทย / Phasa Thai', '0'),
  ('er', 'Tigrinya', 'ትግርኛ', '0'),
  ('tm', 'Turkmen', 'Туркмен / تركمن', '0'),
  ('bw', 'Tswana', 'Setswana', '0'),
  ('to', 'Tonga', 'Lea Faka-Tonga', '0'),
  ('tr', 'Turkish', 'Türkçe', '0'),
  ('ua', 'Ukrainian', 'Українська', '0'),
  ('pk', 'Urdu', 'اردو', '1'),
  ('uz', 'Uzbek', 'Ўзбек', '0'),
  ('vn', 'Vietnamese', 'Tiếng Việt', '0'),
  ('cn', 'Chinese', '中文', '0');");
    }
}
